/**
 * Tokens portados 1:1 dos 3 HTMLs gerados no Stitch (docs/layout/*.html) —
 * design system "Arena Dynamic". Ver docs/layout/ para a fonte original.
 * @type {import('tailwindcss').Config}
 */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#001432",
        outline: "#879484",
        "on-tertiary-fixed": "#00174d",
        "on-secondary-fixed-variant": "#524700",
        primary: "#65a5df",
        "on-tertiary": "#042978",
        "on-primary-fixed": "#000f21",
        tertiary: "#b5c4ff",
        "secondary-fixed": "#ffe243",
        "on-secondary-container": "#716200",
        "inverse-on-surface": "#283044",
        "inverse-primary": "#00226e",
        "error-container": "#93000a",
        "on-secondary": "#393000",
        "on-primary-fixed-variant": "#001b53",
        "surface-container-low": "#131b2e",
        "on-surface-variant": "#bdcab9",
        "primary-fixed-dim": "#65a5df",
        "on-tertiary-fixed-variant": "#25428f",
        "on-background": "#dae2fd",
        "surface-container": "#171f33",
        "secondary-fixed-dim": "#e3c600",
        "secondary-container": "#ffdf0a",
        "tertiary-fixed": "#dbe1ff",
        "primary-container": "#2357a6",
        "surface-bright": "#31394d",
        "on-surface": "#dae2fd",
        "on-primary": "#001539",
        "surface-tint": "#65a5df",
        "tertiary-fixed-dim": "#b5c4ff",
        "surface-variant": "#2d3449",
        surface: "#0b1326",
        "on-error-container": "#ffdad6",
        secondary: "#fffbff",
        "outline-variant": "#3e4a3d",
        "primary-fixed": "#81c4fc",
        "on-tertiary-container": "#00236c",
        "tertiary-container": "#748de0",
        "inverse-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed": "#211b00",
        "on-error": "#690005",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060e20",
        "surface-container-highest": "#2d3449",
        error: "#ffb4ab",
        background: "#0b1326",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "margin-mobile": "16px",
        "container-max-width": "1440px",
        gutter: "24px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ['"Source Sans 3"', "sans-serif"],
        "stats-xl": ["Montserrat", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ['"Source Sans 3"', "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "stats-xl": ["40px", { lineHeight: "40px", fontWeight: "900" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
